<?php

/**
 * Aero
 *
 * Add augmented reality to Magento using Adobe Aero and Apple ArKit.
 *
 * @package ImaginationMedia\Aero
 * @author Igor Ludgero Miura <igor@imaginationmedia.com>
 * @copyright Copyright (c) 2019 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/**
 * @var $this \ImaginationMedia\Aero\Block\Product\View\AugmentedReality
 */

if ($this->hasAugmentedFile()) : ?>
    <div class="augmented-reality" id="augmented-reality" style="display: none;">
        <p><strong><?= __('Test it using Augmented Reality:') ?></strong></p>
        <p class="content">
            <a href="#" rel="ar" id="img-ar-file">
                <img src="#" id="img-ar-preview-file" style="max-width: 140px;">
            </a>
        </p>
    </div>
    <script>
        function iOSversion() {
            if (/iP(hone|od|ad)/.test(navigator.platform)) {
                var v = (navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);
                return parseInt(v[1], 10);
            }
        }

        function isSafari() {
            var ua = navigator.userAgent.toLowerCase();
            if (ua.indexOf('safari') != -1) {
                if (ua.indexOf('chrome') > -1) {
                    return false;
                } else {
                    return true;
                }
            }
        }

        var version = iOSversion();
        if (version !== undefined && version >= 12 && isSafari()) {
            var ajax = new XMLHttpRequest();
            ajax.open("POST", "<?= $this->getPostUrl() ?>", true);
            ajax.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            ajax.send("product_id=<?= $this->getProductId() ?>");
            ajax.onreadystatechange = function() {
                if (ajax.readyState === 4 && ajax.status === 200) {
                    var data = ajax.responseText;
                    data = JSON.parse(data);
                    if (data.has_ar === 1) {
                        document.getElementById("img-ar-file").href = data.ar;
                        document.getElementById("img-ar-preview-file").src = data.preview;
                        document.getElementById("augmented-reality").style.display = "block";
                    }
                }
            };
        }
    </script>
<?php endif; ?>