<?php

/**
 * Aero
 *
 * Add augmented reality to Magento using Adobe Aero and Apple ArKit.
 *
 * @package ImaginationMedia\Aero
 * @author Igor Ludgero Miura <igor@imaginationmedia.com>
 * @copyright Copyright (c) 2019 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/**
 * @var $this \ImaginationMedia\Aero\Block\Product\View\AugmentedReality
 */

if ($this->hasAugmentedFile()) : ?>
    <div class="augmented-reality" id="augmented-reality" style="display: none;">
        <p><strong><?= __('Test it using Augmented Reality:') ?></strong></p>
        <p class="content">
            <a href="#" rel="ar" id="img-ar-file">
                <img src="#" id="img-ar-preview-file" style="max-width: 140px;">
            </a>
        </p>
    </div>
    <script>
        require(["jquery"], function($){
            function iOSversion() {
                if (/iP(hone|od|ad)/.test(navigator.platform)) {
                    var v = (navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);
                    return parseInt(v[1], 10);
                }
            }

            function isSafari() {
                var ua = navigator.userAgent.toLowerCase();
                if (ua.indexOf('safari') != -1) {
                    if (ua.indexOf('chrome') > -1) {
                        return false;
                    } else {
                        return true;
                    }
                }
            }

            if (isSafari() && iOSversion()) {
                var request = jQuery.ajax({
                    url: "<?= $this->getPostUrl() ?>",
                    type: "POST",
                    data: {product_id: "<?= $this->getProductId() ?>"}
                });

                request.done(function (data) {
                    if (data.has_ar === 1) {
                        document.getElementById("img-ar-file").href = data.ar;
                        document.getElementById("img-ar-preview-file").src = data.preview;
                        document.getElementById("augmented-reality").style.display = "block";
                    }
                });
            }
        });
    </script>
<?php endif; ?>